name: Build for Debian 11
on: push


jobs:
  build-deb-11:
    runs-on: self-hosted
    container: golang:1.22-bullseye

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go build
        run: go build -buildvcs=false -o bin/httpleases-deb11

      - name: Check the data
        run: ls -lha $GITHUB_WORKSPACE

      - name: Commit report
        run: |
          git config --global --add safe.directory /__w/httpleases/httpleases
          git config --global user.name 'JKerdreux-imt'
          git config --global user.email 'jkerdreux-imt@users.noreply.github.com'
          git add bin/httpleases-deb11
          git commit -am "Automated report"
          git push
    # 
    #   - name: Push changes
    #     uses: ad-m/github-push-action@master
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
        
      
    
