name: Build latest
on: push

jobs:
  build:
    runs-on: self-hosted
    container: golang:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go build
        run:
          git pull
          go build -buildvcs=false -o bin/httpleases

      - name: Check the data
        run: ls -lha $GITHUB_WORKSPACE/bin

      - name: Commit report
        run: |
          git config --global --add safe.directory /__w/httpleases/httpleases
          git config --global user.name 'JKerdreux-imt'
          git config --global user.email 'jkerdreux-imt@users.noreply.github.com'
          git add bin/httpleases
          git commit -am "Autobuild ${{ github.head_ref }}.${{ github.sha }}"
          git push


  build-deb-11:
    runs-on: self-hosted
    container: golang:1.22-bullseye

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go build
        run: |
          git pull
          go build -buildvcs=false -o bin/httpleases-deb11

      - name: Check the data
        run: ls -lha $GITHUB_WORKSPACE/bin

      - name: Commit report
        run: |
          git config --global --add safe.directory /__w/httpleases/httpleases
          git config --global user.name 'JKerdreux-imt'
          git config --global user.email 'jkerdreux-imt@users.noreply.github.com'
          git add bin/httpleases-deb11
          git commit -am "Autobuild ${{ github.head_ref }}.${{ github.sha }}"
          git push
